/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface BattlePassFactoryInterface extends utils.Interface {
  functions: {
    "craftingProxy()": FunctionFragment;
    "deployBattlePass(uint256)": FunctionFragment;
    "getBattlePassFromUnderlying(uint256)": FunctionFragment;
    "isBattlePassDeployed(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "setOwner(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "craftingProxy"
      | "deployBattlePass"
      | "getBattlePassFromUnderlying"
      | "isBattlePassDeployed"
      | "owner"
      | "setOwner"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "craftingProxy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployBattlePass",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getBattlePassFromUnderlying",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "isBattlePassDeployed",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setOwner",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "craftingProxy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployBattlePass",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBattlePassFromUnderlying",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBattlePassDeployed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setOwner", data: BytesLike): Result;

  events: {
    "BattlePassDeployed(address,uint256)": EventFragment;
    "OwnerUpdated(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BattlePassDeployed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnerUpdated"): EventFragment;
}

export interface BattlePassDeployedEventObject {
  bp: string;
  creatorId: BigNumber;
}
export type BattlePassDeployedEvent = TypedEvent<
  [string, BigNumber],
  BattlePassDeployedEventObject
>;

export type BattlePassDeployedEventFilter =
  TypedEventFilter<BattlePassDeployedEvent>;

export interface OwnerUpdatedEventObject {
  user: string;
  newOwner: string;
}
export type OwnerUpdatedEvent = TypedEvent<
  [string, string],
  OwnerUpdatedEventObject
>;

export type OwnerUpdatedEventFilter = TypedEventFilter<OwnerUpdatedEvent>;

export interface BattlePassFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BattlePassFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    craftingProxy(overrides?: CallOverrides): Promise<[string]>;

    /**
     * This will revert if a BattlePass that accepts the same underlying creatorId has already been deployed.
     * Deploys a new BattlePass which supports a specific underlying creatorId.
     * @param creatorId The creatorId that the BattlePass should accept.
     */
    deployBattlePass(
      creatorId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    /**
     * The BattlePass returned may not be deployed yet. Use isBattlePassDeployed to check.
     * Computes a BattlePass's address from its accepted underlying creatorId
     * @param creatorId The creatorId that the BattlePass should accept.
     */
    getBattlePassFromUnderlying(
      creatorId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    /**
     * This function is useful to check the return values of getBattlePassFromUnderlying, as it does not check that the BattlePass addresses it computes have been deployed yet.
     * Returns if a BattlePass at an address has already been deployed.
     * @param bp The address of a BattlePass which may not have been deployed yet.
     */
    isBattlePassDeployed(
      bp: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    setOwner(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  craftingProxy(overrides?: CallOverrides): Promise<string>;

  /**
   * This will revert if a BattlePass that accepts the same underlying creatorId has already been deployed.
   * Deploys a new BattlePass which supports a specific underlying creatorId.
   * @param creatorId The creatorId that the BattlePass should accept.
   */
  deployBattlePass(
    creatorId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  /**
   * The BattlePass returned may not be deployed yet. Use isBattlePassDeployed to check.
   * Computes a BattlePass's address from its accepted underlying creatorId
   * @param creatorId The creatorId that the BattlePass should accept.
   */
  getBattlePassFromUnderlying(
    creatorId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  /**
   * This function is useful to check the return values of getBattlePassFromUnderlying, as it does not check that the BattlePass addresses it computes have been deployed yet.
   * Returns if a BattlePass at an address has already been deployed.
   * @param bp The address of a BattlePass which may not have been deployed yet.
   */
  isBattlePassDeployed(
    bp: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  setOwner(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    craftingProxy(overrides?: CallOverrides): Promise<string>;

    /**
     * This will revert if a BattlePass that accepts the same underlying creatorId has already been deployed.
     * Deploys a new BattlePass which supports a specific underlying creatorId.
     * @param creatorId The creatorId that the BattlePass should accept.
     */
    deployBattlePass(
      creatorId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    /**
     * The BattlePass returned may not be deployed yet. Use isBattlePassDeployed to check.
     * Computes a BattlePass's address from its accepted underlying creatorId
     * @param creatorId The creatorId that the BattlePass should accept.
     */
    getBattlePassFromUnderlying(
      creatorId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    /**
     * This function is useful to check the return values of getBattlePassFromUnderlying, as it does not check that the BattlePass addresses it computes have been deployed yet.
     * Returns if a BattlePass at an address has already been deployed.
     * @param bp The address of a BattlePass which may not have been deployed yet.
     */
    isBattlePassDeployed(
      bp: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    setOwner(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "BattlePassDeployed(address,uint256)"(
      bp?: null,
      creatorId?: null
    ): BattlePassDeployedEventFilter;
    BattlePassDeployed(
      bp?: null,
      creatorId?: null
    ): BattlePassDeployedEventFilter;

    "OwnerUpdated(address,address)"(
      user?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnerUpdatedEventFilter;
    OwnerUpdated(
      user?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnerUpdatedEventFilter;
  };

  estimateGas: {
    craftingProxy(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * This will revert if a BattlePass that accepts the same underlying creatorId has already been deployed.
     * Deploys a new BattlePass which supports a specific underlying creatorId.
     * @param creatorId The creatorId that the BattlePass should accept.
     */
    deployBattlePass(
      creatorId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    /**
     * The BattlePass returned may not be deployed yet. Use isBattlePassDeployed to check.
     * Computes a BattlePass's address from its accepted underlying creatorId
     * @param creatorId The creatorId that the BattlePass should accept.
     */
    getBattlePassFromUnderlying(
      creatorId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * This function is useful to check the return values of getBattlePassFromUnderlying, as it does not check that the BattlePass addresses it computes have been deployed yet.
     * Returns if a BattlePass at an address has already been deployed.
     * @param bp The address of a BattlePass which may not have been deployed yet.
     */
    isBattlePassDeployed(
      bp: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    setOwner(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    craftingProxy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * This will revert if a BattlePass that accepts the same underlying creatorId has already been deployed.
     * Deploys a new BattlePass which supports a specific underlying creatorId.
     * @param creatorId The creatorId that the BattlePass should accept.
     */
    deployBattlePass(
      creatorId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * The BattlePass returned may not be deployed yet. Use isBattlePassDeployed to check.
     * Computes a BattlePass's address from its accepted underlying creatorId
     * @param creatorId The creatorId that the BattlePass should accept.
     */
    getBattlePassFromUnderlying(
      creatorId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * This function is useful to check the return values of getBattlePassFromUnderlying, as it does not check that the BattlePass addresses it computes have been deployed yet.
     * Returns if a BattlePass at an address has already been deployed.
     * @param bp The address of a BattlePass which may not have been deployed yet.
     */
    isBattlePassDeployed(
      bp: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setOwner(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
